### ISSUE TITLE
插件配置简化

### ISSUE THREAD

**Issue by nooberfsh** [askfiy/nvimrc#1]
首先表示下感谢，最近在知乎上看到你的一系列 neovim 教程，学习了很多，也发现了现在 neovim 的生态是多么的强大。

回到这个 issue， 目前配置插件的方式是这样：
```lua
    {
        -- 显示滚动条
        "petertriho/nvim-scrollbar",
        config = function()
            require("conf.nvim-scrollbar")
        end
    }
```

我的想法是改成这样：
```lua
    {
        -- 显示滚动条
        name = "petertriho/nvim-scrollbar",
        disable = false 
    }
```

在加载插件的时候根据名字自动寻找对应插件的配置文件， 如果有的话就`require`进来。 这样能节省一些行数。。。 

当然这只是我的想法，如果你觉得 ok 的话，我可以提供 PR。

**Comment by askfiy** [comment]
正在修改，预计晚上会发布一个新版本。

配置文件、键位绑定方式都有很大的改变，会加 lazy_load 延迟加载。
